"""
Hardware Task Planner.

Decomposes hardware design tasks into an actionable multi-round research plan.
Every decision is produced by the LLM — no hardcoded keyword decisions.

Research rounds:
  Round 0  →  task decomposition and question enumeration (always)
  Round 1  →  targeted web research for unknown specifications
  Round 2  →  component discovery (if a physical design is required)
  Round 3  →  architecture hypothesis generation (Qwen3-4B)

No hardcoded component names, URLs, architecture names, or task keywords.
"""

from __future__ import annotations

import logging
from typing import Any
from llm.interface import LLMInterface
from agent.prompts import (
    RESEARCH_DECISION_PROMPT,
    TASK_DECOMPOSITION_PROMPT,
    RESEARCH_ROUND_PROMPT,
)

logger = logging.getLogger(__name__)


class ResearchPlan:
    """Structured research plan generated by the planner.

    All fields are populated by the LLM or left as None/empty.
    No hardcoded values are ever injected.
    """

    def __init__(self) -> None:
        # Whether the LLM judged that external web research is required
        self.needs_research: bool = True
        # Human-readable LLM reasoning for the decision
        self.reasoning: str = ""
        # Ordered list of search queries to execute (LLM-generated)
        self.search_queries: list[str] = []
        # Component categories that must be discovered (LLM-generated)
        self.component_categories: list[str] = []
        # Whether the task is physical-design-aware (board-level / chip-level)
        self.physical_design: bool = False
        # Open questions the agent should resolve through research
        self.open_questions: list[str] = []
        # Recommended first action
        self.recommended_action: str = "SEARCH_WEB"
        # Whether the LLM concluded that internal memory is sufficient
        self.memory_sufficient: bool = False

    def to_dict(self) -> dict[str, Any]:
        return self.__dict__.copy()


class HardwarePlanner:
    """Plans hardware design workflows via fully LLM-driven research rounds.

    This planner NEVER uses hardcoded keyword matching or hardcoded
    architecture / component decisions.  Every routing decision is
    generated by the LLM from the raw task description.
    """

    def __init__(self, llm: LLMInterface) -> None:
        self.llm = llm

    # ── Public API ───────────────────────────────────────────────────────

    async def plan(self, task: str) -> ResearchPlan:
        """Full multi-round planning pipeline.

        Round 0: Task decomposition + open question enumeration.
        Round 1: LLM research decision (web vs memory).
        Round 2: If web research is needed, generate focused queries.
        Returns a ResearchPlan with all fields populated from LLM output.
        """
        rp = ResearchPlan()

        # --- Round 0: Decompose the task ---
        decomp = await self._decompose_task(task)
        rp.open_questions = decomp.get("open_questions", [])
        rp.physical_design = decomp.get("physical_design", False)
        rp.component_categories = decomp.get("component_categories", [])

        # --- Round 1: Research decision ---
        decision = await self._decide_research_need(task, rp.open_questions)
        rp.needs_research = decision.get("needs_research", True)
        rp.reasoning = decision.get("reasoning", "")
        rp.memory_sufficient = decision.get("memory_sufficient", False)
        rp.recommended_action = decision.get("recommended_action", "SEARCH_WEB")

        # --- Round 2: Generate targeted queries (only if web research needed) ---
        if rp.needs_research and not rp.memory_sufficient:
            queries = await self._generate_search_queries(task, rp.open_questions, rp.component_categories)
            rp.search_queries = queries

        return rp

    async def decide_research_need(self, task: str) -> dict[str, Any]:
        """Backward-compatible single-round research decision.

        Produces a dict with at minimum:
          needs_research: bool
          reasoning: str
          focused_query: str
          recommended_action: str

        NO hardcoded keyword fallback.  If the LLM call fails, defaults to
        SEARCH_WEB (conservative, never skips needed research).
        """
        rp = await self.plan(task)
        focused_query = rp.search_queries[0] if rp.search_queries else task
        return {
            "needs_research": rp.needs_research,
            "reasoning": rp.reasoning or "LLM-generated decision",
            "focused_query": focused_query,
            "recommended_action": rp.recommended_action,
            "search_queries": rp.search_queries,
            "open_questions": rp.open_questions,
            "component_categories": rp.component_categories,
            "physical_design": rp.physical_design,
            "memory_sufficient": rp.memory_sufficient,
        }

    # ── Private Helpers ──────────────────────────────────────────────────

    async def _decompose_task(self, task: str) -> dict[str, Any]:
        """Round 0: Ask the LLM to enumerate open questions and identify sub-components."""
        prompt = TASK_DECOMPOSITION_PROMPT.format(task=task)
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict):
                return result
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Task decomposition LLM call failed: {exc}")
        # Conservative defaults: treat as unknown, request research
        return {
            "open_questions": [f"What are the hardware specifications for: {task}?"],
            "physical_design": True,
            "component_categories": [],
        }

    async def _decide_research_need(
        self,
        task: str,
        open_questions: list[str],
    ) -> dict[str, Any]:
        """Round 1: LLM decides whether web research is required."""
        questions_str = "\n".join(f"  - {q}" for q in open_questions) or "  (none enumerated)"
        prompt = RESEARCH_DECISION_PROMPT.format(
            task=task,
            open_questions=questions_str,
        )
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict) and "needs_research" in result:
                return result
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Research decision LLM call failed: {exc}")
        # Default: always search (never silently skip research)
        return {
            "needs_research": True,
            "memory_sufficient": False,
            "reasoning": "LLM decision unavailable; defaulting to SEARCH_WEB for safety.",
            "recommended_action": "SEARCH_WEB",
        }

    async def _generate_search_queries(
        self,
        task: str,
        open_questions: list[str],
        component_categories: list[str],
    ) -> list[str]:
        """Round 2: Generate ordered, focused web search queries for each open question."""
        questions_str = "\n".join(f"  - {q}" for q in open_questions) or "  (none)"
        categories_str = ", ".join(component_categories) or "none identified"
        prompt = RESEARCH_ROUND_PROMPT.format(
            task=task,
            open_questions=questions_str,
            component_categories=categories_str,
        )
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict) and "queries" in result:
                queries = result["queries"]
                if isinstance(queries, list):
                    return [str(q) for q in queries if q]
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Search query generation LLM call failed: {exc}")
        # Fallback: one broad query derived from the task itself
        return [task]
