"""
Hardware Task Planner.

Decomposes hardware design tasks into an actionable multi-round research plan.
Every decision is produced by the LLM — no hardcoded keyword decisions.

Research rounds:
  Round 0  →  task decomposition and question enumeration (always)
  Round 1  →  targeted web research for unknown specifications
  Round 2  →  component discovery (if a physical design is required)
  Round 3  →  architecture hypothesis generation (Qwen-14B)

No hardcoded component names, URLs, architecture names, or task keywords.
"""

from __future__ import annotations

import logging
from typing import Any
from llm.interface import LLMInterface
from agent.prompts import (
    RESEARCH_DECISION_PROMPT,
    TASK_DECOMPOSITION_PROMPT,
    RESEARCH_ROUND_PROMPT,
)

logger = logging.getLogger(__name__)


from dataclasses import dataclass, field


@dataclass
class PlanStep:
    """A step within an actionable hardware design and verification plan."""
    id: int
    description: str
    step_type: str
    depends_on: list[int] = field(default_factory=list)
    status: str = "pending"
    result: Any = None


class ResearchPlan:
    """Structured research and execution plan generated by the planner.

    All fields are populated by the LLM or left as None/empty.
    No hardcoded values are ever injected.
    """

    def __init__(self, task: str = "") -> None:
        self.task: str = task
        # Whether the LLM judged that external web research is required
        self.needs_research: bool = True
        # Human-readable LLM reasoning for the decision
        self.reasoning: str = ""
        # Ordered list of search queries to execute (LLM-generated)
        self.search_queries: list[str] = []
        # Component categories that must be discovered (LLM-generated)
        self.component_categories: list[str] = []
        # Whether the task is physical-design-aware (board-level / chip-level)
        self.physical_design: bool = False
        # Open questions the agent should resolve through research
        self.open_questions: list[str] = []
        # Recommended first action
        self.recommended_action: str = "SEARCH_WEB"
        # Whether the LLM concluded that internal memory is sufficient
        self.memory_sufficient: bool = False
        # Concrete execution steps
        self.steps: list[PlanStep] = []

    def build_steps(self) -> None:
        """Derive actionable execution steps from research and task decomposition."""
        self.steps = []
        step_id = 1
        if self.needs_research and self.search_queries:
            for q in self.search_queries[:3]:
                self.steps.append(
                    PlanStep(
                        id=step_id,
                        description=f"Research specification: {q}",
                        step_type="RESEARCH",
                    )
                )
                step_id += 1

        self.steps.append(
            PlanStep(
                id=step_id,
                description="Explore and select hardware architecture candidates",
                step_type="ARCHITECTURE",
                depends_on=[s.id for s in self.steps],
            )
        )
        step_id += 1

        self.steps.append(
            PlanStep(
                id=step_id,
                description="Generate SystemVerilog RTL implementation",
                step_type="RTL",
                depends_on=[step_id - 1],
            )
        )
        step_id += 1

        self.steps.append(
            PlanStep(
                id=step_id,
                description="Lint and syntax verification with Verilator",
                step_type="LINT",
                depends_on=[step_id - 1],
            )
        )
        step_id += 1

        self.steps.append(
            PlanStep(
                id=step_id,
                description="Functional testbench simulation with Cocotb",
                step_type="SIMULATION",
                depends_on=[step_id - 1],
            )
        )
        step_id += 1

        self.steps.append(
            PlanStep(
                id=step_id,
                description="Logic synthesis and resource evaluation with Yosys",
                step_type="SYNTHESIS",
                depends_on=[step_id - 1],
            )
        )

    @property
    def next_step(self) -> Optional[PlanStep]:
        for s in self.steps:
            if s.status == "pending":
                return s
        return None

    def to_dict(self) -> dict[str, Any]:
        return self.__dict__.copy()


class HardwarePlanner:
    """Plans hardware design workflows via fully LLM-driven research rounds.

    This planner NEVER uses hardcoded keyword matching or hardcoded
    architecture / component decisions.  Every routing decision is
    generated by the LLM from the raw task description.
    """

    def __init__(
        self,
        llm: Optional[LLMInterface] = None,
        qwen: Optional[LLMInterface] = None,
        prompts: Optional[dict[str, Any]] = None,
    ) -> None:
        self.llm = llm or qwen
        self.prompts = prompts or {}

    # ── Public API ───────────────────────────────────────────────────────

    async def plan(self, task: str) -> ResearchPlan:
        """Full multi-round planning pipeline.

        Round 0: Task decomposition + open question enumeration.
        Round 1: LLM research decision (web vs memory).
        Round 2: If web research is needed, generate focused queries.
        Returns a ResearchPlan with all fields populated from LLM output.
        """
        rp = ResearchPlan(task=task)

        # --- Round 0: Decompose the task ---
        decomp = await self._decompose_task(task)
        rp.open_questions = decomp.get("open_questions", [])
        rp.physical_design = decomp.get("physical_design", False)
        rp.component_categories = decomp.get("component_categories", [])

        # --- Round 1: Research decision ---
        decision = await self._decide_research_need(task, rp.open_questions)
        rp.needs_research = decision.get("needs_research", True)
        rp.reasoning = decision.get("reasoning", "")
        rp.memory_sufficient = decision.get("memory_sufficient", False)
        rp.recommended_action = decision.get("recommended_action", "SEARCH_WEB")

        # --- Round 2: Generate targeted queries (only if web research needed) ---
        if rp.needs_research and not rp.memory_sufficient:
            queries = await self._generate_search_queries(task, rp.open_questions, rp.component_categories)
            rp.search_queries = queries

        rp.build_steps()
        return rp

    async def decompose(self, task: str, context: str = "") -> ResearchPlan:
        """Decompose task into actionable hardware research and design plan."""
        return await self.plan(task)

    @staticmethod
    def _plan_to_text(plan: Any) -> str:
        """Convert a ResearchPlan or plan object into structured text for context."""
        if plan is None:
            return "No active plan."
        lines = []
        if getattr(plan, "reasoning", None):
            lines.append(f"Reasoning: {plan.reasoning}")
        if getattr(plan, "open_questions", None):
            lines.append("Open Questions:")
            for q in plan.open_questions:
                lines.append(f"  - {q}")
        if getattr(plan, "search_queries", None):
            lines.append("Search Queries:")
            for s in plan.search_queries:
                lines.append(f"  - {s}")
        if getattr(plan, "steps", None):
            lines.append("Execution Steps:")
            for st in plan.steps:
                lines.append(f"  [{st.id}] {st.description} ({st.status})")
        return "\n".join(lines) if lines else str(plan)

    async def decide_research_need(self, task: str) -> dict[str, Any]:
        """Backward-compatible single-round research decision.

        Produces a dict with at minimum:
          needs_research: bool
          reasoning: str
          focused_query: str
          recommended_action: str

        NO hardcoded keyword fallback.  If the LLM call fails, defaults to
        SEARCH_WEB (conservative, never skips needed research).
        """
        rp = await self.plan(task)
        focused_query = rp.search_queries[0] if rp.search_queries else task
        return {
            "needs_research": rp.needs_research,
            "reasoning": rp.reasoning or "LLM-generated decision",
            "focused_query": focused_query,
            "recommended_action": rp.recommended_action,
            "search_queries": rp.search_queries,
            "open_questions": rp.open_questions,
            "component_categories": rp.component_categories,
            "physical_design": rp.physical_design,
            "memory_sufficient": rp.memory_sufficient,
        }

    # ── Private Helpers ──────────────────────────────────────────────────

    async def _decompose_task(self, task: str) -> dict[str, Any]:
        """Round 0: Ask the LLM to enumerate open questions and identify sub-components."""
        prompt = TASK_DECOMPOSITION_PROMPT.format(task=task)
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict):
                return result
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Task decomposition LLM call failed: {exc}")
        # Conservative defaults: treat as unknown, request research
        return {
            "open_questions": [f"What are the hardware specifications for: {task}?"],
            "physical_design": True,
            "component_categories": [],
        }

    async def _decide_research_need(
        self,
        task: str,
        open_questions: list[str],
    ) -> dict[str, Any]:
        """Round 1: LLM decides whether web research is required."""
        questions_str = "\n".join(f"  - {q}" for q in open_questions) or "  (none enumerated)"
        prompt = RESEARCH_DECISION_PROMPT.format(
            task=task,
            open_questions=questions_str,
        )
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict) and "needs_research" in result:
                return result
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Research decision LLM call failed: {exc}")
        # Default: always search (never silently skip research)
        return {
            "needs_research": True,
            "memory_sufficient": False,
            "reasoning": "LLM decision unavailable; defaulting to SEARCH_WEB for safety.",
            "recommended_action": "SEARCH_WEB",
        }

    async def _generate_search_queries(
        self,
        task: str,
        open_questions: list[str],
        component_categories: list[str],
    ) -> list[str]:
        """Round 2: Generate ordered, focused web search queries for each open question."""
        questions_str = "\n".join(f"  - {q}" for q in open_questions) or "  (none)"
        categories_str = ", ".join(component_categories) or "none identified"
        prompt = RESEARCH_ROUND_PROMPT.format(
            task=task,
            open_questions=questions_str,
            component_categories=categories_str,
        )
        try:
            result = await self.llm.generate_json(prompt)
            if isinstance(result, dict) and "queries" in result:
                queries = result["queries"]
                if isinstance(queries, list):
                    return [str(q) for q in queries if q]
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Search query generation LLM call failed: {exc}")
        # Fallback: one broad query derived from the task itself
        return [task]

    async def replan(self, current_plan: Any, error_context: str) -> ResearchPlan:
        """Replan research/architecture trajectory upon hitting max retries or failures."""
        logger.info(f"Replanning due to error: {error_context[:200]}")
        task_str = getattr(current_plan, "task", "") or str(current_plan)
        # Generate refined queries focusing on resolving the specific error observed
        open_questions = [f"How to fix hardware failure: {error_context[:200]} in {task_str}"]
        rp = ResearchPlan()
        rp.open_questions = open_questions
        rp.needs_research = True
        rp.recommended_action = "SEARCH_WEB"
        if self.llm:
            try:
                queries = await self._generate_search_queries(task_str, open_questions, [])
                rp.search_queries = queries
            except Exception as e:
                logger.warning(f"Replan search query generation failed: {e}")
                rp.search_queries = [f"{task_str} fix {error_context[:100]}"]
        else:
            rp.search_queries = [f"{task_str} fix {error_context[:100]}"]
        return rp


# Canonical alias ensuring backwards and forwards compatibility
Planner = HardwarePlanner
__all__ = ["HardwarePlanner", "Planner", "ResearchPlan"]
