"""
Git Tool — version control for hardware designs.

Auto-commits design iterations, tags successful designs,
manages branches for design variants, and provides
diff capabilities for design comparison.
"""

from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger(__name__)


class GitTool:
    """Git wrapper for managing hardware design versions.

    Each design iteration is a commit. Successful designs
    are tagged with their reward scores.
    """

    def __init__(self, config: dict[str, Any] | None = None):
        config = config or {}
        self.repo_path = config.get("designs_repo", "./designs")
        self.auto_commit = config.get("auto_commit", True)
        self.tag_on_success = config.get("tag_on_success", True)

        self._repo = None
        self._init_repo()

    def _init_repo(self) -> None:
        """Initialize or open the Git repository."""
        try:
            import git
            os.makedirs(self.repo_path, exist_ok=True)

            try:
                self._repo = git.Repo(self.repo_path)
                logger.info(f"Opened existing repo: {self.repo_path}")
            except git.InvalidGitRepositoryError:
                self._repo = git.Repo.init(self.repo_path)
                logger.info(f"Initialized new repo: {self.repo_path}")

                # Create initial commit
                readme_path = os.path.join(self.repo_path, "README.md")
                with open(readme_path, "w") as f:
                    f.write("# Hardware Designs\n\nGenerated by Self-Evolving Chip Agent\n")
                self._repo.index.add(["README.md"])
                self._repo.index.commit("Initial commit")

        except ImportError:
            logger.warning("GitPython not installed — Git features disabled")
            self._repo = None

    # ── Commit ───────────────────────────────────────────────────────

    def commit_design(
        self,
        name: str,
        message: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str | None:
        """Commit all changes in the designs directory.

        Args:
            name: Design name for the commit message
            message: Optional custom commit message
            metadata: Optional metadata to include in commit message

        Returns:
            Commit hash, or None if no changes or Git unavailable
        """
        if self._repo is None:
            return None

        try:
            # Stage all changes
            self._repo.index.add("*")

            # Check if there are changes to commit
            if not self._repo.is_dirty(untracked_files=True):
                logger.debug("No changes to commit")
                return None

            # Add untracked files
            untracked = self._repo.untracked_files
            if untracked:
                self._repo.index.add(untracked)

            # Build commit message
            if not message:
                message = f"Design iteration: {name}"
                if metadata:
                    message += "\n\n"
                    for k, v in metadata.items():
                        message += f"  {k}: {v}\n"

            commit = self._repo.index.commit(message)
            logger.info(f"Committed: {commit.hexsha[:8]} — {name}")
            return commit.hexsha

        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return None

    # ── Tagging ──────────────────────────────────────────────────────

    def tag_design(self, tag_name: str, message: str = "") -> bool:
        """Tag the current commit.

        Args:
            tag_name: Tag name (e.g., "alu_v1_reward_0.95")
            message: Optional tag message

        Returns:
            True if tagging succeeded
        """
        if self._repo is None:
            return False

        try:
            self._repo.create_tag(tag_name, message=message)
            logger.info(f"Tagged: {tag_name}")
            return True
        except Exception as e:
            logger.error(f"Git tag failed: {e}")
            return False

    # ── Branching ────────────────────────────────────────────────────

    def create_variant(self, branch_name: str) -> bool:
        """Create a new branch for a design variant.

        Args:
            branch_name: Branch name for the variant

        Returns:
            True if branch was created successfully
        """
        if self._repo is None:
            return False

        try:
            self._repo.create_head(branch_name)
            self._repo.heads[branch_name].checkout()
            logger.info(f"Created and checked out branch: {branch_name}")
            return True
        except Exception as e:
            logger.error(f"Branch creation failed: {e}")
            return False

    def switch_variant(self, branch_name: str) -> bool:
        """Switch to an existing design variant branch."""
        if self._repo is None:
            return False

        try:
            self._repo.heads[branch_name].checkout()
            logger.info(f"Switched to branch: {branch_name}")
            return True
        except Exception as e:
            logger.error(f"Branch switch failed: {e}")
            return False

    # ── Diffing ──────────────────────────────────────────────────────

    def diff_versions(self, commit_a: str, commit_b: str = "HEAD") -> str:
        """Get the diff between two versions.

        Args:
            commit_a: First commit hash (or tag)
            commit_b: Second commit hash (default: HEAD)

        Returns:
            Unified diff string
        """
        if self._repo is None:
            return ""

        try:
            return self._repo.git.diff(commit_a, commit_b)
        except Exception as e:
            logger.error(f"Git diff failed: {e}")
            return ""

    # ── History ──────────────────────────────────────────────────────

    def get_history(self, max_count: int = 20) -> list[dict[str, str]]:
        """Get recent commit history.

        Returns:
            List of {hash, message, date} dicts
        """
        if self._repo is None:
            return []

        try:
            commits = []
            for commit in self._repo.iter_commits(max_count=max_count):
                commits.append({
                    "hash": commit.hexsha[:8],
                    "message": commit.message.strip().split("\n")[0],
                    "date": commit.committed_datetime.isoformat(),
                    "author": str(commit.author),
                })
            return commits
        except Exception as e:
            logger.error(f"Git history failed: {e}")
            return []
